services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.11-ubi8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      
      MONGO_INITDB_DATABASE: chatbot
      
    restart: always